apiVersion: v1
kind: Secret
metadata:
  name: urlvy-secrets
  namespace: urlvy
type: Opaque
stringData:
  # set these to your real values (mine is not provided here)
  DATABASE_URL: "postgres://urlvy:password@your-rds-endpoint:5432/urlvy_db"
  JWT_SECRET:    "your_jwt_secret"
  GOOGLE_API_KEY: "your_google_gemini_key"
